import type { Compound } from "./types";

export const COMPOUNDS: Compound[] = [
  {
    id: "bpc-157",
    name: "BPC-157",
    alternate_names: ["Body Protection Compound 157"],
    category: "Recovery",
    regulatory_status: "Research compound",
    research_status: "Preclinical, limited human data",
    mechanism_summary:
      "Synthetic pentadecapeptide derived from a gastric protein sequence. Preclinical work describes effects on angiogenic signalling and tissue repair pathways.",
    half_life_value: 4,
    half_life_unit: "hours",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Ranges reported in literature vary widely. Not personalized guidance.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    alternate_names: ["Ozempic", "Wegovy"],
    category: "GLP-1 and incretin-related",
    regulatory_status: "Approved medication",
    research_status: "Multiple phase III trials",
    mechanism_summary:
      "GLP-1 receptor agonist. Described in literature as affecting glucose-dependent insulin secretion, gastric emptying, and appetite signalling.",
    half_life_value: 165,
    half_life_unit: "hours",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Prescribing information defines ranges. Follow your own instructions.",
    evidence_quality: "Substantial",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    alternate_names: ["Mounjaro", "Zepbound"],
    category: "GLP-1 and incretin-related",
    regulatory_status: "Approved medication",
    research_status: "Multiple phase III trials",
    mechanism_summary:
      "Dual GIP and GLP-1 receptor agonist described in literature as affecting glycaemic control and appetite signalling.",
    half_life_value: 120,
    half_life_unit: "hours",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Prescribing information defines ranges. Follow your own instructions.",
    evidence_quality: "Substantial",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    alternate_names: [],
    category: "Growth-hormone secretagogues",
    regulatory_status: "Research compound",
    research_status: "Preclinical and small human studies",
    mechanism_summary:
      "Selective ghrelin receptor agonist described in literature as influencing pulsatile growth hormone release.",
    half_life_value: 2,
    half_life_unit: "hours",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Reported research ranges vary. Educational only.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "cjc-1295",
    name: "CJC-1295",
    alternate_names: ["Modified GRF (1-29)"],
    category: "Growth-hormone secretagogues",
    regulatory_status: "Research compound",
    research_status: "Limited human data",
    mechanism_summary:
      "Growth hormone releasing hormone analogue described in literature as extending GHRH signalling duration.",
    half_life_value: 30,
    half_life_unit: "minutes",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Reported research ranges vary. Educational only.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "tb-500",
    name: "TB-500",
    alternate_names: ["Thymosin beta-4 fragment"],
    category: "Recovery",
    regulatory_status: "Research compound",
    research_status: "Preclinical",
    mechanism_summary:
      "Peptide fragment associated in preclinical literature with actin regulation and cell migration.",
    half_life_value: 10,
    half_life_unit: "hours",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Reported research ranges vary. Educational only.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "nad-plus",
    name: "NAD+",
    alternate_names: ["Nicotinamide adenine dinucleotide"],
    category: "Longevity and research",
    regulatory_status: "Compounded medication",
    research_status: "Early human research",
    mechanism_summary:
      "Coenzyme involved in redox reactions and sirtuin-related pathways described across metabolic literature.",
    half_life_value: null,
    half_life_unit: "",
    half_life_source: "Not established in reviewed sources.",
    educational_ranges: "Not established. Educational only.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
  {
    id: "aod-9604",
    name: "AOD-9604",
    alternate_names: [],
    category: "Body composition",
    regulatory_status: "Investigational compound",
    research_status: "Human trials with mixed outcomes",
    mechanism_summary:
      "Modified fragment of human growth hormone studied for effects on lipid metabolism.",
    half_life_value: 30,
    half_life_unit: "minutes",
    half_life_source: "Sample content. Not a verified source.",
    educational_ranges: "Reported research ranges vary. Educational only.",
    evidence_quality: "Limited",
    references: ["Sample reference entry. Replace with verified citations."],
    last_reviewed_at: "2026-07-01",
    is_custom: false,
  },
];

export const CATEGORIES = Array.from(new Set(COMPOUNDS.map((c) => c.category)));

export const SITES: { key: string; label: string; side: "front" | "back"; x: number; y: number }[] =
  [
    { key: "abd_ul", label: "Upper-left abdomen", side: "front", x: 41, y: 45 },
    { key: "abd_ur", label: "Upper-right abdomen", side: "front", x: 59, y: 45 },
    { key: "abd_ll", label: "Lower-left abdomen", side: "front", x: 41, y: 53 },
    { key: "abd_lr", label: "Lower-right abdomen", side: "front", x: 59, y: 53 },
    { key: "thigh_l", label: "Left thigh", side: "front", x: 42, y: 70 },
    { key: "thigh_r", label: "Right thigh", side: "front", x: 58, y: 70 },
    { key: "arm_l", label: "Left upper arm", side: "front", x: 24, y: 36 },
    { key: "arm_r", label: "Right upper arm", side: "front", x: 76, y: 36 },
    { key: "glute_l", label: "Left glute", side: "back", x: 42, y: 58 },
    { key: "glute_r", label: "Right glute", side: "back", x: 58, y: 58 },
    { key: "back_arm_l", label: "Left triceps", side: "back", x: 24, y: 38 },
    { key: "back_arm_r", label: "Right triceps", side: "back", x: 76, y: 38 },
  ];

export const siteLabel = (key: string | null) =>
  SITES.find((s) => s.key === key)?.label ?? "Not recorded";
