/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as VialsRouteImport } from './routes/vials'
import { Route as WeeklyReviewRouteImport } from './routes/weekly-review'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryCompoundIdRouteImport } from './routes/library.$compoundId'
import { Route as ProtocolsIndexRouteImport } from './routes/protocols.index'
import { Route as ProtocolsProtocolIdRouteImport } from './routes/protocols.$protocolId'
import { Route as ProtocolsNewRouteImport } from './routes/protocols.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const VialsRoute = VialsRouteImport.update({
  id: '/vials',
  path: '/vials',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyReviewRoute = WeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCompoundIdRoute = LibraryCompoundIdRouteImport.update({
  id: '/library/$compoundId',
  path: '/library/$compoundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsIndexRoute = ProtocolsIndexRouteImport.update({
  id: '/protocols/',
  path: '/protocols/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsProtocolIdRoute = ProtocolsProtocolIdRouteImport.update({
  id: '/protocols/$protocolId',
  path: '/protocols/$protocolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsNewRoute = ProtocolsNewRouteImport.update({
  id: '/protocols/new',
  path: '/protocols/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calculator': typeof CalculatorRoute
  '/handoff': typeof HandoffRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/timeline': typeof TimelineRoute
  '/vials': typeof VialsRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library/': typeof LibraryIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calculator': typeof CalculatorRoute
  '/handoff': typeof HandoffRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/timeline': typeof TimelineRoute
  '/vials': typeof VialsRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library': typeof LibraryIndexRoute
  '/protocols': typeof ProtocolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calculator': typeof CalculatorRoute
  '/handoff': typeof HandoffRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/timeline': typeof TimelineRoute
  '/vials': typeof VialsRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library/': typeof LibraryIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/calculator'
    | '/handoff'
    | '/onboarding'
    | '/paywall'
    | '/progress'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/vials'
    | '/weekly-review'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library/'
    | '/protocols/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/calculator'
    | '/handoff'
    | '/onboarding'
    | '/paywall'
    | '/progress'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/vials'
    | '/weekly-review'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library'
    | '/protocols'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/calculator'
    | '/handoff'
    | '/onboarding'
    | '/paywall'
    | '/progress'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/vials'
    | '/weekly-review'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library/'
    | '/protocols/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CalculatorRoute: typeof CalculatorRoute
  HandoffRoute: typeof HandoffRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  TimelineRoute: typeof TimelineRoute
  VialsRoute: typeof VialsRoute
  WeeklyReviewRoute: typeof WeeklyReviewRoute
  LibraryCompoundIdRoute: typeof LibraryCompoundIdRoute
  ProtocolsProtocolIdRoute: typeof ProtocolsProtocolIdRoute
  ProtocolsNewRoute: typeof ProtocolsNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ProtocolsIndexRoute: typeof ProtocolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vials': {
      id: '/vials'
      path: '/vials'
      fullPath: '/vials'
      preLoaderRoute: typeof VialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-review': {
      id: '/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof WeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$compoundId': {
      id: '/library/$compoundId'
      path: '/library/$compoundId'
      fullPath: '/library/$compoundId'
      preLoaderRoute: typeof LibraryCompoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/': {
      id: '/protocols/'
      path: '/protocols'
      fullPath: '/protocols/'
      preLoaderRoute: typeof ProtocolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/$protocolId': {
      id: '/protocols/$protocolId'
      path: '/protocols/$protocolId'
      fullPath: '/protocols/$protocolId'
      preLoaderRoute: typeof ProtocolsProtocolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/new': {
      id: '/protocols/new'
      path: '/protocols/new'
      fullPath: '/protocols/new'
      preLoaderRoute: typeof ProtocolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CalculatorRoute: CalculatorRoute,
  HandoffRoute: HandoffRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  TimelineRoute: TimelineRoute,
  VialsRoute: VialsRoute,
  WeeklyReviewRoute: WeeklyReviewRoute,
  LibraryCompoundIdRoute: LibraryCompoundIdRoute,
  ProtocolsProtocolIdRoute: ProtocolsProtocolIdRoute,
  ProtocolsNewRoute: ProtocolsNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ProtocolsIndexRoute: ProtocolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
