/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as VialsRouteImport } from './routes/vials'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryCompoundIdRouteImport } from './routes/library.$compoundId'
import { Route as ProtocolsIndexRouteImport } from './routes/protocols.index'
import { Route as ProtocolsProtocolIdRouteImport } from './routes/protocols.$protocolId'
import { Route as ProtocolsNewRouteImport } from './routes/protocols.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const VialsRoute = VialsRouteImport.update({
  id: '/vials',
  path: '/vials',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCompoundIdRoute = LibraryCompoundIdRouteImport.update({
  id: '/library/$compoundId',
  path: '/library/$compoundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsIndexRoute = ProtocolsIndexRouteImport.update({
  id: '/protocols/',
  path: '/protocols/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsProtocolIdRoute = ProtocolsProtocolIdRouteImport.update({
  id: '/protocols/$protocolId',
  path: '/protocols/$protocolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsNewRoute = ProtocolsNewRouteImport.update({
  id: '/protocols/new',
  path: '/protocols/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/sites': typeof SitesRoute
  '/vials': typeof VialsRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library/': typeof LibraryIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/sites': typeof SitesRoute
  '/vials': typeof VialsRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library': typeof LibraryIndexRoute
  '/protocols': typeof ProtocolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/sites': typeof SitesRoute
  '/vials': typeof VialsRoute
  '/library/$compoundId': typeof LibraryCompoundIdRoute
  '/protocols/$protocolId': typeof ProtocolsProtocolIdRoute
  '/protocols/new': typeof ProtocolsNewRoute
  '/library/': typeof LibraryIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/onboarding'
    | '/progress'
    | '/sites'
    | '/vials'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library/'
    | '/protocols/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/onboarding'
    | '/progress'
    | '/sites'
    | '/vials'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library'
    | '/protocols'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/onboarding'
    | '/progress'
    | '/sites'
    | '/vials'
    | '/library/$compoundId'
    | '/protocols/$protocolId'
    | '/protocols/new'
    | '/library/'
    | '/protocols/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SitesRoute: typeof SitesRoute
  VialsRoute: typeof VialsRoute
  LibraryCompoundIdRoute: typeof LibraryCompoundIdRoute
  ProtocolsProtocolIdRoute: typeof ProtocolsProtocolIdRoute
  ProtocolsNewRoute: typeof ProtocolsNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ProtocolsIndexRoute: typeof ProtocolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vials': {
      id: '/vials'
      path: '/vials'
      fullPath: '/vials'
      preLoaderRoute: typeof VialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$compoundId': {
      id: '/library/$compoundId'
      path: '/library/$compoundId'
      fullPath: '/library/$compoundId'
      preLoaderRoute: typeof LibraryCompoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/': {
      id: '/protocols/'
      path: '/protocols'
      fullPath: '/protocols/'
      preLoaderRoute: typeof ProtocolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/$protocolId': {
      id: '/protocols/$protocolId'
      path: '/protocols/$protocolId'
      fullPath: '/protocols/$protocolId'
      preLoaderRoute: typeof ProtocolsProtocolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/new': {
      id: '/protocols/new'
      path: '/protocols/new'
      fullPath: '/protocols/new'
      preLoaderRoute: typeof ProtocolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SitesRoute: SitesRoute,
  VialsRoute: VialsRoute,
  LibraryCompoundIdRoute: LibraryCompoundIdRoute,
  ProtocolsProtocolIdRoute: ProtocolsProtocolIdRoute,
  ProtocolsNewRoute: ProtocolsNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ProtocolsIndexRoute: ProtocolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
